In [15]:
import pandas as pd
import os

# Define a function to extract semester and year from file name
def extract_semester_year(filename):
    parts = filename.split('.')

    semester = parts[0][-4:-2].upper() 
    year = int('20'+parts[0][-2:])       
    return semester, year

# Create an empty list to store dataframes
dfs = []

# Iterate through each file in the directory
for filename in os.listdir('./data'):
    # print(filename)
    # Read the CSV file into a dataframe
    df = pd.read_csv(f'./data/{filename}')
    # Extract semester and year from filename
    semester, year = extract_semester_year(filename)
    # Add semester and year columns to dataframe
    df['Semester'] = semester
    df['Year'] = year
    # Append the modified dataframe to the list
    dfs.append(df)

# Concatenate all dataframes into a single dataframe
combined_df = pd.concat(dfs, ignore_index=True)

# Write the combined dataframe to a CSV file
combined_df.to_csv('combined_schedule.csv', index=False)

In [16]:
combined_df.head()

,Area,Course #,Sect #,Course Title,Instructor / Teaching Team,Time,Delivery Mode,Credits,Enroll Limits,Waitlist,...,Location for Instr Delivery or Staging of Materials,Section #,Degree Requirement Note,Location: MAC\n(unless noted otherwise),Curriculum Role,Unnamed: 12,Unnamed: 13,Location: MAC\n(unless noted\notherwise),Credit s,Unnamed: 11
0,AHS,AHSE0112,01,AHSE0112: The Olin Conductorless Orchestra: Bu...,"Dabby, Diana",R 6-8pm,Fully Remote,1,no cap,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AHS,AHSE2199A,01,"AHSE2199A: Special Topics in Arts, Humanities ...","Lynch, Caitrin; Martello, Rob",Tues & Fri 10-11:30am,Fully Remote,4,no cap,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AHS,AHSE2199B,01,"AHSE2199B: Special Topics in Arts, Humanities ...","Keizer, Arlene",MW 2-3:30pm,Fully Remote,4,35,yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AHS,AHSE2199C,01,"AHSE2199C: Special Topics in Arts, Humanities ...","Adler, Jon; Epstein, Gillian",TR 10-11:30am,Fully Remote,4,20,yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AHS,AHSE3190,01,"AHSE3190: Arts, Humanities, Social Science Pre...","Epstein, Gillian",NaN,Fully Remote,1,50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN